services:
  zerovim-dev-container:
    container_name: zerovim-dev-container
    build:
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ../:/home/zerovim/.config/nvim
      - ../../web/eventprofil/:/home/zerovim/eventprofil
