-- https://github.com/OXY2DEV/markview.nvim
return {}
-- return {
--   "https://github.com/OXY2DEV/markview.nvim",
--   lazy = false,
--   dependencies = {
--     "saghen/blink.cmp",
--   },
--   preview = {
--     icon_provider = "mini", -- "internal"
--   },
-- }
